### ISSUE TITLE
void function meow-layout

### ISSUE THREAD

**Issue by owensys** [DogLooksGood/meow#1]
Environment: emacs28.0, terminal, linuxmint
use -q to startup, setup code:
``` lisp
(add-to-list 'load-path "/home/somacs/packages/dash")
(add-to-list 'load-path "/home/somacs/packages/meow")
(require 'cl-lib)
(require 'meow)
(meow-global-mode 1)
(meow-layout 'dvorak)
```
eval-buffer will got a error:
Symbol’s function definition is void: meow-layout

**Comment by DogLooksGood** [comment]
示例中使用的 use-package, 对应的 :custom 是变量的设置。所以你需要

`(setq meow-layout 'dvorak)`

**Comment by owensys** [comment]
ok, now works fine.
