### ISSUE TITLE
More documents

### ISSUE THREAD

**Issue by KiteAB** [DogLooksGood/meow#10]
Meow has 84 variables and 153 functions now, but I don't want to look at the use of these variables one by one. So can write a **detailed** document for this package?

**Comment by KiteAB** [comment]
And ivy-posframe has some bugs when using meow (
![](https://ftp.bmp.ovh/imgs/2020/12/9c7313c8e55961d9.png)

**Comment by DogLooksGood** [comment]
Yes, I can reproduce the bug. I'll investigate and fix.

I think I have developing a lot in dev branch. And the document, I think I need a weekend.

**Comment by KiteAB** [comment]
Oh thx, I'll close this issue after this weekend and trying dev branch!

**Comment by KiteAB** [comment]
And how do I display states status in my awesome tray?

**Comment by DogLooksGood** [comment]
Well, for me, meow should be a ultimate solution for all editing requirements, I use meow to editing, navigation, search and etc. But it doesn't mean there's no plan to make meow working with other packages.  However, I'm focusing on make it reliable, well-featured, and well-documented. 

If you wanna give a try, you probably want to checkout the `dev` branch, and function `meow-minimal-indicator` can give a some text which can be used in mode-line. Here's an example:

https://github.com/DogLooksGood/.emacs.d/blob/master/elisp/init-laf.el#L57

And this is my whole configuration for meow, and I love it.

https://github.com/DogLooksGood/.emacs.d/blob/master/elisp/init-modal.el

**Comment by KiteAB** [comment]
> Well, for me, meow should be an ultimate solution for all editing requirements, I use meow to editing, navigation, search and etc. But it doesn't mean there's no plan to make meow working with other packages. However, I'm focusing on make it reliable, well-featured, and well-documented.
> 
> If you wanna give a try, you probably want to checkout the `dev` branch, and function `meow-minimal-indicator` can give you the text which can be used in mode-line. Here's an example:
> 
> https://github.com/DogLooksGood/.emacs.d/blob/master/elisp/init-laf.el#L57
> 
> And this is my whole configuration for meow, and I love it.
> 
> https://github.com/DogLooksGood/.emacs.d/blob/master/elisp/init-modal.el

Perfect

**Comment by KiteAB** [comment]
Fixed, so close

**Comment by DogLooksGood** [comment]
Anyway, I think I finish the job of refactoring and the first version of new document.
