### ISSUE TITLE
Defining "c-c d" occurs a error: Key sequence c - c d starts with non-prefix key c

### ISSUE THREAD

**Issue by lczch** [DogLooksGood/meow#14]
I try to:
```
(global-set-key (kbd "c-c d") 'counsel-descbinds)
```
error: Key sequence c - c d starts with non-prefix key c.

Why this occurs?

**Comment by DogLooksGood** [comment]
Hi, I think there's nothing with Meow. You should use  `C-c`(A capital C) not `c-c`.

**Comment by lczch** [comment]
Thanks!
