### ISSUE TITLE
Keypad 好像不能处理 <delete> <up> <down> <left> <right> <backspace>

### ISSUE THREAD

**Issue by meziberry** [DogLooksGood/meow#15]
例如： M-<left>  C-M-<up> 等按键。 在 M- 等待后续按键时，按  <left> <up> 是光标移动，而不是触发命令。

**Comment by DogLooksGood** [comment]
已经在 0752b4637e3fac9cc3e7e2525ad6d090487b46d7 修复

**Comment by meziberry** [comment]
真快啊。工作正常。
