### ISSUE TITLE
When in a term-mode

### ISSUE THREAD

**Issue by rxf4el** [DogLooksGood/meow#17]
How do i disable meow-mode when i'm in an ansi-term or eshell,  since i cannot use space on those modes.

**Comment by DogLooksGood** [comment]
```
(add-to-list 'meow-normal-state-mode-list 'term-mode)
;; eshell-mode already in this list
```
You should add `term-mode` to `meow-normal-state-mode-list`, which will by default enable NORMAL mode instead of MOTION mode.

**Comment by rxf4el** [comment]
thanks
