### ISSUE TITLE
Customize meow cursor face

### ISSUE THREAD

**Issue by KiteAB** [DogLooksGood/meow#19]
i probably know how to change the face in emacs, but how can i change the cursor type in insert mode??? i know i can add a hook to change the cursor type, but there's a face:
```emacs-lisp
(describe-face meow-insert-cursor) ;; Change type like (setq-default cursor-type '(bar . 2))
(describe-face meow-motion-cursor) ;; Change color like (set-cursor-color "blue")
```

**Comment by DogLooksGood** [comment]
```
(defvar meow-cursor-type-default 'box)
(defvar meow-cursor-type-normal 'box)
(defvar meow-cursor-type-motion 'box)
(defvar meow-cursor-type-insert '(bar . 4))
(defvar meow-cursor-type-keypad 'hollow)
```
Change these variables.

**Comment by DogLooksGood** [comment]
If everything works correctly, you will see the cursor changed by Meow depends on modal state. If this doesn't work, you probably found a bug :(

**Comment by KiteAB** [comment]
i mean meow correctly change the cursor type when switching state, but i want to switch different cursor styles in different states

**Comment by DogLooksGood** [comment]
Okay, then you just custom those variables.

**Comment by KiteAB** [comment]
> Okay, then you just custom those variables.

The "variables"?

**Comment by DogLooksGood** [comment]
The type of cursor is not decided by face, it is decided by a variable `cursor-type`. So meow will set `cursor-type` at the proper timing with  `meow-cursor-type-***`.

see https://github.com/DogLooksGood/meow/blob/master/meow-util.el#L68-L90.

And the cursor color can be changed via `set-cursor-color` function(Emacs built-in API), so cursor color is not set by face neither. 
Why Meow use faces for cursor color is because a face can inherit from other face. 

If you want cursor in INSERT mode be a bar with width 1pixel and color red. you need:

```emacs-lisp
(custom-set-faces
 '(meow-insert-cursor ((t (:background "red")))))

(setq meow-cursor-type-insert '(bar . 1))
```

If you want the color of cursor, inherit from, maybe font-lock-keyword-face, you can do this:
```emacs-lisp
(custom-set-faces
 '(meow-insert-cursor ((t (:inherit font-lock-keyword-face)))))
```
As you can see, you don't have to set cursor color for every themes, just make them inherit from some existing faces.

**Comment by KiteAB** [comment]
> The type of cursor is not decided by face, it is decided by a variable `cursor-type`. So meow will set `cursor-type` at the proper timing with `meow-cursor-type-***`.
> 
> see https://github.com/DogLooksGood/meow/blob/master/meow-util.el#L68-L90.
> 
> And the cursor color can be changed via `set-cursor-color` function(Emacs built-in API), so cursor color is not set by face neither.
> Why Meow use faces for cursor color is because a face can inherit from other face.
> 
> If you want cursor in INSERT mode be a bar with width 1pixel and color red. you need:
> 
> ```emacs-lisp
> (custom-set-faces
>  '(meow-insert-cursor ((t (:background "red")))))
> 
> (setq meow-cursor-type-insert '(bar . 1))
> ```
> 
> If you want the color of cursor, inherit from, maybe font-lock-keyword-face, you can do this:
> 
> ```emacs-lisp
> (custom-set-faces
>  '(meow-insert-cursor ((t (:inherit font-lock-keyword-face)))))
> ```
> 
> As you can see, you don't have to set cursor color for every themes, just make them inherit from some existing faces.

oh i've focused on these faces about meow, thx!

**Comment by NoahStoryM** [comment]
> If you want the color of cursor, inherit from, maybe font-lock-keyword-face, you can do this:
> ```emacs-lisp
> (custom-set-faces
>  '(meow-insert-cursor ((t (:inherit font-lock-keyword-face)))))
> ```
> As you can see, you don't have to set cursor color for every themes, just make them inherit from some existing faces.

The approach didn't work for me. After examing the source code, I discovered why:
```emacs-lisp
(defun meow--read-cursor-face-color (face)
  "Read cursor color from face."
  (let ((f (face-attribute face :inherit)))
    (if (equal 'unspecified f)
        (let ((color (face-attribute face :background)))
          (if (equal 'unspecified color)
              (face-attribute 'default :foreground)
            color))
      (meow--read-cursor-face-color f))))
```

The function checks the `:inherit` attribute first. If it's `unspecified`, it then looks for the `:background` color. This means that simply inheriting from another face won't work as expected.

The solution is to explicitly set the background color instead:
```emacs-lisp
(custom-set-faces
 `(meow-insert-cursor ((t (:inherit unspecified :background ,(face-attribute 'font-lock-keyword-face :foreground))))))
```
