### ISSUE TITLE
关于color-rg-mode等衍生mode的问题

### ISSUE THREAD

**Issue by liuyinz** [DogLooksGood/meow#22]
您好，我看了变量meow-normal-state-mode-list中已经添加了 text-mode，但是我使用的color-rg-mode属于text-mode 的衍生mode，尽管我添加了
```
(use-package color-rg
    :hook (color-rg-mode-hook . meow-motion-mode))
```
但是进入color-rg-mode后，仍然处于meow-normal-mode，不知如何解决？

**Comment by DogLooksGood** [comment]
Hi, 这样的方式应该是不行的，因为 meow 正常启动的话在所有的 buffer 中都会先激活 meow-mode, 再根据具体的情况激活对应的 mode。 一个可行的方式是参照 meow 对 wgrep 的处理方式。

https://github.com/DogLooksGood/meow/blob/master/meow-shims.el#L86-L115

利用 advice，在指定的模式下进行切换。
