### ISSUE TITLE
[suggestion] base generating cheatsheets on XKB keycodes instead of characters

### ISSUE THREAD

**Issue by moesasji** [DogLooksGood/meow#30]
I really like having the option to have quick access to a "cheatsheet" that shows me what commands that are bound. Looking at how this is currently implemented in [meow-cheatsheet.el](https://github.com/DogLooksGood/meow/blob/master/meow-cheatsheet.el) there are some limitations in the approach you picked:

1) You implicitly assume that the user is using an [iso-layout](https://upload.wikimedia.org/wikipedia/commons/b/b2/Physical_keyboard_layouts_comparison_ANSI_ISO_KS_ABNT_JIS.png). However there are more physical layouts out there, with ansi pretty much the default in Europe. 
2) The placement of certain symbols is country-specific; despite the layout still being called qwerty, etc (with the amount of countries you get a scary amount of duplication)
3) Even your supported Colemak layout has a couple of pretty popular variations see for example: [mod-dh](https://colemakmods.github.io/mod-dh/keyboards.html) 
4) A significant fraction of those tempted to running "meow" are probably using customized keyboard layouts; those users would need to patch the code of meow to get their layout and I doubt you want to add too many uncommon layouts to your code.

The bottom-line is that the above things combined very quickly become very hard or even impossible to manage if one for every variation would need to add a customized variant to `meow-cheatsheet.el`. 

To avoid this issue to an extend I think it would be worth basing the generation of cheatsheets on [XKB key-codes](https://www.charvolant.org/doug/xkb/html/node5.html) (look mainly at [this figure](https://www.charvolant.org/doug/xkb/html/img3.png)) instead. Using these keycodes in your templates instead of the `letters/symbols` would avoid a lot of unnecessary duplication as these key-codes will be the same for iso, ansi, etc. Effectively you would just have one of [these](https://github.com/DogLooksGood/meow/blob/master/meow-cheatsheet.el#L37) for each of the layouts you want to support from iso, ansi, etc. if you replace the characters with the corresponding level for the key-code on that key.

As this explanation is probably difficult to follow: my thinking is that you can use the same approach as done used by XKB and have arrays in the form (adapted for emacs lisp)

```
xkb_symbols "qwerty" {
...
    key <AD01> { [ q, Q ] };
    key <AD02> { [ w, W ] };
    key <AD03> { [ e, E  ] };
    key <AD04> { [ r, R ] };
    key <AD05> { [ t, T ] };
    key <AD06> { [ y, Y ] };
....
}
```
The first would be the unshifted character, the second the shifted character.... basing things on these types of arrays would make it easier to support different layouts as this array tells you the physical position as well as the characters that are on the key. Moreover tackling this in this way has the added benefit that you could expose the above array (adapted to emacs) to the users in case they run a different keyboard layout. Just defining the array would allow that user to have their dedicated cheatsheet without having to add layouts to meow itself.

btw) if you think think this is worth implementing it is probably worth keeping in mind that XKB can have more than two levels that can be used. Essentially the symbols typed with AltGr are on level3.

**Comment by DogLooksGood** [comment]
Sounds reasonable.

So we could have:
1. Templates for each physical keyboard layouts. 
2. Mappings mapping from XKB keycode to key names for each keyboard layout.

Let user specify their physical keyboard layout(iso, ansi, etc) and keyboard layout(qwerty, dvorak, etc). If user use a layout that Meow doesn't ship with, just provide a mapping(an array).

Am I understand correctly?

**Comment by moesasji** [comment]
You indeed understood exactly what I was trying to explain. Essentially XKB allows defining a layout by specifying what to put on each physical key.

btw) Might help to see a full example of a layout: [this](https://github.com/moesasji/xkeyboard-config/commit/23fdb4a6966fd65b98b1fd303cfaecf8fcae8556) is how I set my own layout. In your case you would probably want to have users put in the symbols themselves.

**Comment by DogLooksGood** [comment]
I wonder should we create cheatsheet.el in a separate package, for general usages, not limited in Meow.

**Comment by moesasji** [comment]
> Should we create cheatsheet.el in a separate package, for general usages, not limited to Meow.

I don't remember ever seeing a general purpose package in emacs having that functionality so that sounds indeed like something you could consider doing. The risk you run is that for the use as a general purpose package in emacs people might also want the cheatsheet to show CTRL, ALT, ALT+META bindings as well, something like you see in [this ergoemacs image](https://ergoemacs.github.io/ergoemacs-extras/ergo-layouts/ergoemacs-layout-us.png)

**Comment by DogLooksGood** [comment]
I'm considering user can toggle the display with keys, for example, c for C-, m for M-, or custom prefix for nested keymaps.

**Comment by DogLooksGood** [comment]
So we can have something like this?
```

┏━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━━━━┓
┃  <TLDE> │  <AE01> │  <AE02> │  <AE03> │  <AE04> │  <AE05> │  <AE06> │  <AE07> │  <AE08> │  <AE09> │  <AE10> │  <AE11> │  <AE12> │      <BKSP> ┃
┃         |         |         |         |         |         |         |         |         |         |         |         |         |             ┃
┠─┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┤             ┃
┃         │         │         │         │         │         │         │         │         │         │         │         │         │             ┃
┃         |         |         |         |         |         |         |         |         |         |         |         |         |             ┃
┠─────────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────┴───┬─────────┨
┃       <TAB> │  <AD01> │  <AD02> │  <AD03> │  <AD04> │  <AD05> │  <AD06> │  <AD07> │  <AD08> │  <AD09> │  <AD10> │  <AD11> │  <AD12> │  <BKSL> ┃
┃             |         |         |         |         |         |         |         |         |         |         |         |         |         ┃
┃             ├┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┨
┃             │         │         │         │         │         │         │         │         │         │         │         │         │         ┃
┃             |         |         |         |         |         |         |         |         |         |         |         |         |         ┃
┠─────────────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─┬───────┴─────────┨
┃               │  <AC01> │  <AC02> │  <AC03> │  <AC04> │  <AC05> │  <AC06> │  <AC07> │  <AC08> │  <AC09> │  <AC10> │  <AC11> │          <RTRN> ┃
┃               |         |         |         |         |         |         |         |         |         |         |         │                 ┃
┃               ├┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┤                 ┃
┃               │         │         │         │         │         │         │         │         │         │         │         │                 ┃
┃               |         |         |         |         |         |         |         |         |         |         |         |                 ┃
┠───────────────┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────┬───┴─────────────────┨
┃                     │  <AB01> │  <AB02> │  <AB03> │  <AB04> │  <AB05> │  <AB06> │  <AB07> │  <AB08> │  <AB09> │  <AB10> │                     ┃
┃                     |         |         |         |         |         |         |         |         |         |         |                     ┃
┃                     ├┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┤                     ┃
┃                     │         │         │         │         │         │         │         │         │         │         │                     ┃
┃                     |         |         |         |         |         |         |         |         |         |         |                     ┃
┗━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━╅─────────┴─────────┴─────────┴─────────╆━━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━┛
                                                    ┃                                <SPCE> ┃
                                                    ┃                                       ┃
                                                    ┃                                       ┃
                                                    ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

**Comment by moesasji** [comment]
Just for clarity: I don't think you want to show things like <AC10> in the output of the cheatsheet, so I assume this would be your template?

My thinking is that you would want to replace keys like <AC01> with the first character in your array (= 'a' for qwerty); the shifted character would be the second character (= 'A"). So you probably need to have something that gives you the shifted character as well? (this is primarily as there is no obvious link for the shifted numbers/symbols)

Note that it would be great to put the modifiers in as well (I have characters on the right shift)

btw) the idea on toggling with keys to show nested keymaps could work very well!

**Comment by DogLooksGood** [comment]
Hey, I just updated and add `meow-cheatsheet-physical-layout`. 
Now, the user can specify
```
(setq meow-cheatsheet-physical-layout meow-cheatsheet-physical-layout-ansi)
(setq meow-cheatsheet-layout meow-cheatsheet-layout-dvp)
```

Currently, only `ansi` is added because I don't know about other layouts. could you help me with the `iso` layout?

**Comment by DogLooksGood** [comment]
I did not separate it as a package, mainly because it's hard to display the original command name, each grid has only 9 chars' width. So commands in Meow have been shorten(hard coded), so that it can be put into a grid.

**Comment by DogLooksGood** [comment]
Okay, I think we don't have to cover every layout. Having an extensible solution is enough for now.
