### ISSUE TITLE
cursor update posthook function is no-op?

### ISSUE THREAD

**Issue by moesasji** [DogLooksGood/meow#35]
Looking for something else I spotted that since commit ecf5147c the [meow--on-post-command-hook](https://github.com/DogLooksGood/meow/blob/8c613a65cdb90e05504affe6067bf75722833239/meow-util.el#L208) function is a noop. 

As it doesn't seem to be used at all in the rest of the code it looks like the function should be deleted?

**Comment by DogLooksGood** [comment]
Yes, I'll deleted.

**Comment by DogLooksGood** [comment]
deleted.
