### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by zenny** [DogLooksGood/meow#4]
@DogLooksGood Just wanted to experiment with this one as it seems like a better option than kakoune.el. Thanks for creating something.

Trying to install as described in the Readme using melpa in scimax, but the upstream reports the archive was not available:

```
Error (use-package): Failed to install meow: https://melpa.org/packages/meow-20200626.1804.tar: Not found
```

A nice usage guideline with the keybinding list would be a great addition, imho. Thanks.

Cheers, and stay safe,
/z

**Comment by DogLooksGood** [comment]
Hmm, I think I should update readme to have a complete keybinding list.

**Comment by zenny** [comment]
This got solved with a solution described in here (https://github.com/jkitchin/scimax/issues/376) and here (https://github.com/melpa/melpa/issues/7025).

Cheers,

**Comment by zenny** [comment]
> Hmm, I think I should update readme to have a complete keybinding list.

Look forward to. :D
