### ISSUE TITLE
meow-line-expand 有些不符合预期

### ISSUE THREAD

**Issue by nick357** [DogLooksGood/meow#44]
我使用时感觉meow-line-expand和meow-line没什么区别。
对比meow-left-expand之类的，可以用光标的移动上下左右来扩大和减少选区，改变选区的方向。
看看能不能支持这种方式，降低心智负担编辑更加高效。

**Comment by DogLooksGood** [comment]
你通常不太需要 `meow-line-expand` 这个命令，xxx-expand 命令是会保留你现有的选择的，类似于 
```
foo foo [ foo
foo foo ] foo
```
比如当前你有个这样的选择，`meow-line-expand` 把当前光标在的一行加到原来的选择中。所有的 -expand 都是指这个意思。

**Comment by nick357** [comment]
理解了，但扩大和缩小meow-line这种行选区，能提供一套按向上和向下移动键的方式。来实现meow-left-expand差不多的行为吗。这样是不是按键更加精简。

**Comment by nick357** [comment]
我看了下源码，应该是meow-left之类的移动函数选择性的退出了选区模式。用emacs的移动函数则体验一致。
想问下这个是基于什么考虑呢？有了i、a退出选区模式进入插入模式，是不是单独搞个两个函数从normal进入和退出选区模式体验更好。

**Comment by nick357** [comment]
后来思考了下meow的选择的还是在normal里，不存在选择模式也很合理，按键绑定也是normal的，只是有些状态可以导致按相同按键，调用相同函数时候行为不一致。既然字符选择状态下meow改变了移动的行为为扩展选区，哪在行选模式下或块选模式下是否都保持一致会更好。

**Comment by DogLooksGood** [comment]
https://github.com/DogLooksGood/meow/issues/38

其实这里有比较详细的讨论。

* 概括：
Meow 根据命令的使用频率，把移动分成了3组（不算`beginning/end/bound/inner-of-thing` 这四个命令）。

频率最高的是字符移动，有4个基础命令，`meow-left/right/prev/next`。每个方向上都有一个独立的按键。他们各有一个 -expand 版本。

频率次高的是词/符号，有6个命令，`meow-mark/back/next-word/symbol`，这六个命令都没有 -expand 版本，取而代之的是，除了前后两个方向外，额外的 `meow-mark-word/symbol` 是用来直接选整个词或符号，同时激活 expand 类型选择。你可以通过 `M-x (meow--selection-type)` 看到当前的选择类型。类型分 expand 和 select 两类，比如 `(expand . word)` 的选择，如果后续是 word 类型的移动，就能直接扩展。而 `(select . word)` 的类型，就不会被扩展。

频率再低一档的有，`meow-line`, `meow-block`, `meow-find`, `meow-till`, `meow-join`, `meow-search`, 这些命令要反向的话可以通过 `negative-argument`(<kbd>-</kbd>) 或是 `meow-reverse`，他们大多都有 -expand 版本。

* 什么样的命令会继承当前选择
所有的 -expand 命令，包括  `meow-expand`。

* 什么样的命令会创建可继承的选择
通常 -expand 版本，都会创建 expand 类型的选择（除了 `meow-find-expand`, `meow-till-expand`）。非 -expand 的命令也可能创建 expand 类型的选择，比如 `meow-line`。

**Comment by nick357** [comment]
感谢你这么详细的解释其中设计的理念。
词/符号这6个命令不带-expand，不提供选区扩展十分好理解。
频率再低一档的有，meow-line, meow-block, meow-find, meow-till, meow-join, meow-search这些的-expand版本提供的操作能力完全与meow-left-expand相似。这个为什么不能保持一致性，反而引入了`negative-argument(-) `有些不是太好理解。

**Comment by DogLooksGood** [comment]
一个命令的正反向和 expand 加起来实际上是 4 个，正向，正向expand，反向，反向expand。如果想都能有不错的位置，那只能借用到 Ctrl 或 Alt 中的一个修饰键。但是用了修饰键，1. 可能会和 Emacs 内置的命令冲突，2. 组合键，比如 <kbd>M-f</kbd> 实际上也是两个键。所以不如直接用 negative-argument, 这样也是两个键，而且是只要保证先后，不用协调的(修饰键有释放时机要求)

**Comment by DogLooksGood** [comment]
还有就是词/符号是有办法扩展的，先 mark 再 back/next 就可以。

**Comment by DogLooksGood** [comment]
还有就是词/符号是有办法扩展的，先 mark 再 back/next 就可以。

**Comment by DogLooksGood** [comment]
哦，还有一个，缩小可以用 meow-pop，所有命令都可以。

**Comment by DogLooksGood** [comment]
如果没有更多的问题，我先关闭这个 issue 了。
