### ISSUE TITLE
find 和 till 向前和向后的行为不一致

### ISSUE THREAD

**Issue by driftcrow** [DogLooksGood/meow#48]
find 向前寻找时光标会在目标字符后，till则在目标字符上，但是按；后进行反向寻找时则反过来了，find会在目标字符上，till 则在目标字符后。这是有意设置的吗？

**Comment by DogLooksGood** [comment]
emacs 的光标机制和 vim 是有区别的，vim 的光标是落在字符上的，而 emacs 的光标可以理解为落在两个字符中间，显示在后面的光标上。

find 是越过要找的字符，till 是止步于要找的字符。

**Comment by driftcrow** [comment]
没有和vim作比较，就是meow的同一个命令向前运行，和反方向运行的行为结果不一致

**Comment by DogLooksGood** [comment]
![image](https://user-images.githubusercontent.com/11796018/120127252-76d6cd80-c1f1-11eb-97c4-3adfb0cae419.png)
这是正向的 find f, 位置是 f 的后面
![image](https://user-images.githubusercontent.com/11796018/120127298-95d55f80-c1f1-11eb-95b5-cd7289e2f727.png)
这是正向的 till f，位置是 f 的前面
![image](https://user-images.githubusercontent.com/11796018/120127312-a4237b80-c1f1-11eb-83c7-ab07675d869a.png)
这是反向的 find s，位置是 s 的前面
![image](https://user-images.githubusercontent.com/11796018/120127338-bac9d280-c1f1-11eb-996e-464e54956df5.png)
这是反向的 till s，位置是 s 的后面

**Comment by driftcrow** [comment]
终于搞清楚了，感谢这么耐心解答
