### ISSUE TITLE
Specific to qwerty keyboard and bar cursor

### ISSUE THREAD

**Issue by zenny** [DogLooksGood/meow#5]
@DogLooksGood 

A querty-related readme would be appreciated.

Like in kakoune, how can one change the cursor look from pipe `|` in insert mode to bar in command mode?

Cheers,

**Comment by DogLooksGood** [comment]
Hi, the cursor style should change automatically when you toggle modes.

I'm not clear what you mean by `pipe` and `bar`, I think there are only `bar`, `hbar` and `box` for cursor style.

**Comment by zenny** [comment]
> Hi, the cursor style should change automatically when you toggle modes. It's probably a bug if it doesn't work as intended.
> 
> I'm not clear what you mean by `pipe` and `bar`, I think there are only `bar`, `hbar`, `box`, `hollow` for cursor style.

I meant the cursor look from bar (for `I`nsert mode), box (for `N`ormal mode) and hollow (for `K`ommand mode) so that each time one does not have to look at the modeline to confirm the mode s/he is in. Thanks

**Comment by DogLooksGood** [comment]
I think it's a good idea, let me make a change.

BTW, there's a function called `meow-indicator` which can be used in mode-line. 

![image](https://user-images.githubusercontent.com/11796018/87937683-bf006c00-cac7-11ea-8735-b68f390192b2.png)

Besides, I haven't done any theme/mode-line related work for Meow yet.

**Comment by zenny** [comment]
> I think it's a good idea, let me make a change.
> 
> BTW, there's a function called `meow-indicator` which can be used in mode-line.
> 
> ![image](https://user-images.githubusercontent.com/11796018/87937683-bf006c00-cac7-11ea-8735-b68f390192b2.png)
> 
> Besides, I haven't done any theme/mode-line related work for Meow yet.

Thanks, but `M-x meow-indicator` did not result the mode as it was in your screenshot. Would you mind sharing your emacs config? Thanks.

**Comment by DogLooksGood** [comment]
I use a very simple mode-line customized for myself. `meow-indicator` is not a command, it's function to use in `mode-line-format`. If you don't use your own mode-line, something is still missing to integrate meow with those mode-line packages. 

BTW, meow will change cursor colors in different mode.

**Comment by zenny** [comment]
> I use a very simple mode-line customized for myself. `meow-indicator` is not a command, it's function to use in `mode-line-format`. If you don't use your own mode-line, something is still missing to integrate meow with those mode-line packages.

Got it! any pointer how to use `meow-indicator` with smart-mode-line?

> 
> The theme is also made for myself, not complete yet.

Nifty work! 

> 
> BTW, meow will change cursor colors in different mode.

Different colors are fine, but prefer different shapes (some people have problem seeing colors with conditions with color blindness and tetrachromat).

Thanks!

**Comment by DogLooksGood** [comment]
I've made an update to allow customization on cursor-type for different modes.
And the cursor in `KEYPAD` now has a default `hollow` type.
