### ISSUE TITLE
与key-chord一起使用时modeline显示错误

### ISSUE THREAD

**Issue by x2zh** [DogLooksGood/meow#51]
## 环境信息：
key-chord 版本：20201222.2030  配置：
```emacs-lisp
(use-package key-chord
  :ensure t
  :config
  (key-chord-mode 1)
  (key-chord-define-global ",." [escape])
```

meow 版本：20210601.156  配置为readme中的qwerty键盘的默认配置

## 错误描述：
在 insert 模式下按键 `,.` 后，normal模式下的按键已经生效了，但是 modeline 上显示的模式还是 `INSERT`
期望结果：modeline 显示 `NORMAL`

**Comment by DogLooksGood** [comment]
Fixed in 99a35c4b15ff2a10896352baecd54b0fde8daa03
