### ISSUE TITLE
[question/feature] Is it possible to change the LEADER key?

### ISSUE THREAD

**Issue by AndersonTorres** [DogLooksGood/meow#52]
Hello!

First, I want to say this package is awesome! I am using it a couple of weeks, and I think its concept is amazing. Complex and a bit intricate, but it has an understandable logic behind it. The possibilities of customization are huge but not insurmountable.

Now, I want to ask: is it possible to choose another LEADER key besides SPC?

It would be interesting for me to use INSERT as a key for that LEADER role, instead of SPC. 
This is mostly a matter of personal taste, but I would like to explain my rationale anyway:

The INSERT key is not very useful:  when it is pressed, Emacs changes to a very annoying overwrite mode, a rarely needed functionality nowadays. On the other hand, Emacs opens the possibility of customization for this key (and for any key, for that matter).

I have made a quick&dirty search in the code, but I have not found how to customize this LEADER key. That being said,

1. how can it be done?
2. if this is not possible, can you add a feature to customize this LEADER key?

Thanks in advance!

**Comment by DogLooksGood** [comment]
Hi, thank you for the nice words, and I'm glad you like it.

This is how you use INSERT as leader-key.
```
(define-key meow-normal-state-keymap [insert] meow-leader-keymap)
(define-key meow-motion-state-keymap [insert] meow-leader-keymap)
```
Even though Meow provides some helper functions, but `meow-normal/motion/insert/keypad-state-keymap` are just plain, simple Emacs keymap. You can customize them by whatever way you want.  There's no command called `meow-leader`, instead you bind `meow-leader-keymap` to whatever key you like.

And if you don't need <kbd>SPC</kbd> as leader anymore, just unbind it.
```
(define-key meow-normal-state-keymap (kbd "SPC") nil)
(define-key meow-motion-state-keymap (kbd "SPC") nil)
```

If you want to check the code, see `meow-keymap.el`.

**Comment by DogLooksGood** [comment]
Is your problem solved? so we can close this issue.

**Comment by AndersonTorres** [comment]
To be honest, no. There is a small issue:

In Keypad state, the SPC key is still employed as modifier. Looking at the example of Section 5 in [readme](https://github.com/DogLooksGood/meow#5-keypad-all-those-commands-without-modifiers), the expected outcome should be something like "Vanilla `C-h k` is mapped to `[insert] h [insert]`, but the second `[insert]` is treated like an insert key, not as a modifier.

Is there another place when the SPC key is still read as modifier?

**Comment by DogLooksGood** [comment]
Hi, in KEYPAD state the SPC is not a leader, it is called "literal prefix", controlled by variable `meow--keypad-literal-prefix`.

To use INSERT as literal prefix, you need these setup.
```
;; introduce INSERT key into KEYPAD state
(define-key meow-keypad-state-keymap [insert] 'meow-keypad-self-insert)
;; use INSERT as literal prefix
(defvar meow--keypad-literal-prefix 'insert)
```

**Comment by DogLooksGood** [comment]
I just rename prefix varables and add doc for them.

https://github.com/DogLooksGood/meow/blob/master/CUSTOMIZATIONS.md#meow-keypad-literal-prefix

Additionally INSERT key is added into keypad keymap by default.

**Comment by AndersonTorres** [comment]
Now Meow works as expected!
Many thanks!

... and apologies for my bad English skills.

**Comment by DogLooksGood** [comment]
Never mind, your English is good!
