### ISSUE TITLE
meow-kmacro-lines在kmacro定义结束后不执行kmacro

### ISSUE THREAD

**Issue by Dicridon** [DogLooksGood/meow#54]
作者你好，我在emacs china上面看到你的这个插件，被里面kmacro的部分吸引了就想试一试，我照着你给出来的gif图试了一下，但是始终不能做出你的编辑效果。

我的场景和你的foo的多行编辑例子类似，有若干行文本，我需要在这几行文本前后各增加一些新的文本，比如从下面
```
foo
foo
foo
```
变成
```
checking foo, done
checking foo, done
checking foo, done
```
我操作的流程是先用行选选中了三行foo（这里用的是`meow-line`），然后调用`meow-kmacro-lines`，这个时候我的光标回到了第一行，并且我看到minibuffer提示正在定义kmacro，我在把第一行从`foo`变成`checking foo, done`之后，不管是用`C-x )`结束kmacro定义还是调用`meow-end-or-call-kmacro`，都不能让后面两行也变成`checking foo, done`。我看了好几次`meow`的readme，但是都没有找到具体的操作教程，所以想问一下我是不是对`meow-kmacro-lines`的使用方式理解不对以及这个功能应该怎么用呢？
下图是我的keybinding。
![image](https://user-images.githubusercontent.com/24477137/122343444-483e4e00-cf78-11eb-9b86-52d25a3cc3cf.png)
另外如果这个问题不是特别蠢的话，我可能可以帮忙补充一下kmacro部分的readme？

**Comment by DogLooksGood** [comment]
那个早期演示的 gif 和现在的行为有一些出入，我先说明下现在的行为，再说下原因。（确保你使用的版本老的版本）

# 当前行为
录制 kmacro 和结束录制，就用 Emacs 自带的命令就好。比如说你用 f3 录制，f4 结束。

`meow-kmacro-lines`, `meow-kmacro-matches` 两个命令是按不同的方式去重放 kmacro 的。对于 `meow-kmacro-lines` 你选择一些行，然后执行这个命令即可。

所以现在的操作方式是在第一个 foo 的行首，f3 开始录制 , 修改之后 f4 结束录制。然后选下面的要应用的行，用 `meow-kmacro-lines` 重放。

# 当前行为的变化原因
早期的设计有很多 Do-What-I-Mean 风格的命令，在不同场景有不同表现。之前能立刻执行 kmacro 是通过了 DWIM 的结束录制命令实现的。后来 Meow 去掉了所有 DWIM 风格的命令，让每个命令专注一件事。现在的 `meow-end-or-call-kmacro` 仅仅是 `kmacro-end-or-call-macro` 命令的别名（预留出来以备后面有补充一些逻辑的需要）。

所有 Kmacro 相关的文档在 https://github.com/DogLooksGood/meow/blob/master/KMACROS.md。

所有和文档相关的工作或建议都非常欢迎！

**Comment by Dicridon** [comment]
抱歉昨天后面有一点事情，然后现在才回复。
我试了一下，首先把`meow`更新到了`20210612.304`版本，然后按照您给出的说明，确实是可以正常使用了，非常感谢作者大大的说明。
另外，在我使用过程中观察到`meow-kmacro-lines`的行为好像可能会出现一些比较奇怪的情况，我下面列举一下正常的和不正常的场景。例子依然是把
```
foo
foo
foo
```
变成
```
checking foo, done
checking foo, done
checking foo, done
```
## 第一种正常的操作
光标移动至第一行foo，进入插入模式，然后开始记录kmacro，完成后不回到normal mode，直接用`C-SPC`选出我想要处理的行，然后手动调用`meow-kmacro-lines`，此时可以成功获得期望的结果。

## 第二种正常的操作
处于normal mode，光标移动至第一行foo，开始记录kmacro，**kmacro最后一步是ESC回到normal mode**，然后结束kmacro的记录。之后用`meow-line`选出需要的行并用绑定的keybinding调用`meow-kmacro-lines`（我使用的`X`作为`meow-kmacro-lines`）的快捷键。此时可以获得期望的结果。

## 不正常的操作
处于normal mode，光标移动至第一行foo，开始记录kmacro，**然后结束kmacro的记录，按ESC回到normal mode**。之后用`meow-line`选出需要的行并用绑定的keybinding调用`meow-kmacro-lines`（我使用的`X`作为`meow-kmacro-lines`）的快捷键。此时输出会变成
```
checking foo, done
ichecking foo, done
ichecking foo, done
```
多出来的`i`我理解是因为记录macro的时候把开始的`i`进入insert mode也给记录进去了，但是kmacro结尾又没有匹配ESC来退出insert mode，这个应该是我自己用法的问题。但此时我看到`meow`的状态提示为normal mode，但实际上我处于insert mode（`meow`的所有keybinding都失效了），这个时候按ESC，`meow`的状态提示没有变化，但实际上我从insert mode回到了normal mode。这个情况是不是一个“预期”的bug呢（用户使用的方式不对所以出现了状态栏和实际状态不一致的情况）？

**Comment by DogLooksGood** [comment]
是会有这个问题，因为 kmacro 本身只关注着键盘的输入。我觉得这个问题的各种情况很多，比较好的一个解决的办法就是只在 normal 下使用 kmacro 录制和结束的按键。比如在 normal 下绑定两个键，而不是使用全局的快捷键。

在 normal 下开始，然后操作，最后在 normal 下结束。

两个解决的办法
### 靠按键绑定规避
从按键绑定上可以一定程度规避掉误操作的情况，比如解绑全局的 f3, f4 等等，重新在 normal 上设置按键等等。但 meow 里面并没有做这些设置。

### 靠在 meow 的 kmacro 命令上做些逻辑来规避。
例如如果当前不是 normal 或 motion 模式，这两个命令就无效，这样的方式。我更倾向于这样做。

**Comment by Dicridon** [comment]
好的，那我就没什么问题了，那我整理一下kmacro的使用细节，补充到`meow`的文档内？

**Comment by DogLooksGood** [comment]
容我先做一点修改，按照我刚才的方案二。

**Comment by Dicridon** [comment]
我这边更新了一下，感觉现在使用起来比之前自然了非常多，而且操作上也很符合人的直觉，前面碰到的问题也都没有了。
