### ISSUE TITLE
meow-block should work on curly braces or at least allow configuration to do so

### ISSUE THREAD

**Issue by eko234** [DogLooksGood/meow#57]
I'm really liking your package so far, I was wondering if it is posible to implement this behaviour (make meow-block work in curly braces) or maybe provide a way to configure the pairs to match with, it would be useful if people were working with tags or other kind of surrounding patterns, maybe the pairs could also be regexes to allow more powerful customizations, I don't know if it goes out of the scope of the project, but I was just wondering, thanks.

**Comment by DogLooksGood** [comment]
Hi, does `curly braces` means `{}`?
`meow-block` use `\\s)` and `\\s(` to search for parentheses. `\\s)` and `\\s(` means the character treated as parentheses in current major mode.
So in Emacs Lisp mode, `{}` is not treated as a pair of parentheses, but in C mode, it is.
And `<>` is not a pair of parentheses in Emacs Lisp mode, but in Java mode, it is.

It is welcomed, if you'd like to provide a PR to support customize this regexp. But by default, meow-block should only detect those meaningful parentheses depending on major mode.

**Comment by DogLooksGood** [comment]
I'll close for now, since there's no more discussion.
