### ISSUE TITLE
meow-change-save doesn't change char and some questions

### ISSUE THREAD

**Issue by repelliuss** [DogLooksGood/meow#58]
`meow-change-save` doesn't change when on a char but `meow-change` does. It seems like you do an extra `region-active-p` check on `meon-change-save`.

and I have some questions,

1. How do you select a comment block? What do you think about making it a thing?
2. Is it possible to define a custom thing?
3. Why aren't there expand variants of meow-*-of-thing? For example `meow-end-of-thing`.
4. I surfed through the issues, translated some of the Chinese issues and I saw that you were explaining your reasoning and other many things in greater details. Do you plan to add those to README?
5. Finally, can I extend this issue if I have more questions or would you like their own issues? :smile:

Thanks for meow!

**Comment by DogLooksGood** [comment]
Hi!

By default `meow-change` won't work when there's no region, and in Meow a modification command either work without region or with a region. What you see is the fallback command behavior. `meow-change` will fallback to `meow-change-char` when there's no region. This behavior is customizable through `meow-selection-command-fallback`. The `meow-change-save` should support a fallback behavior, but not implemented. Consider it a bug.

# For question 1 & 2

I don't select comment block directly. But it's possible to make it a thing and Emacs has a thing called comment. Adding a custom comment thing should be easy, check M-: `(thing-at-point 'comment)`. To define a custom thing in Meow, two steps. 

1. Register a thing by giving it two functions. see https://github.com/DogLooksGood/meow/blob/master/meow-thing.el#L220
2. Give the thing a key via `meow-char-thing-table`. see: https://github.com/DogLooksGood/meow/blob/master/meow-var.el#L79

# For question 3

I don't think there's a strong need for expand on `meow-*-of-thing`. I'm glad to know your use cases.

# For question 4

I see the problem of current README, it's doesn't explain the idea behind meow clearly. I think a overhaul is needed for document. Simply adding some answers into README only make it harder to understand IMO.

# For question 5

Sure, it's okay to extend. Do it the way you like!

**Comment by repelliuss** [comment]
Thanks!

I don't have any _real_ use cases but will say when I have.

I'll reopen this and update the title if I have more questions so we can close this right now.
