### ISSUE TITLE
Disabling meow-global-mode should also disable the setup-indicator 

### ISSUE THREAD

**Issue by vimsux** [DogLooksGood/meow#59]
Disabling meow-global-mode should also disable the setup-indicator.
Now it just remains visible, showing NORMAL in the mode line.

**Comment by DogLooksGood** [comment]
Fixed! 25f5686393ccbfef7cfc85442afdc150a57a3822

Thanks for the advice!

**Comment by vimsux** [comment]
Hi, thanks, but there is still something wrong.
(meow-setup-indicator) will add an empty space " " to the mode line even if meow has not been enabled
something wrong in meow-setup-indicator, i guess

**Comment by DogLooksGood** [comment]
Hi, `meow-setup-indicator` will update the variable `mode-line-format`, it should be considered as a helper function, it's not smart enough to handle all the cases. It's your responsibility to call it at right place. 

User's mode line format can be very complex, you have to customize it manually if you want something special. What you need is something like
```
(:eval
 (when (bound-and-true-p meow-mode)
   (meow-indicator)))
```
