### ISSUE TITLE
keypad mode binding issue

### ISSUE THREAD

**Issue by bdarcus** [DogLooksGood/meow#60]
Hi - I just learned about this package, and so trying it out.

I use vertico, consult and embark for completion functionality, and have a variety of bound consult commands, including `C-x b` for `consult-buffer`, as you can see here:

![image](https://user-images.githubusercontent.com/1134/129463304-16f9d570-07ad-4189-8a7e-2fefaa5f6fdb.png)

But when I use keypad mode, and do `SPC x` to get the pop-up, it shows the `C-x b` binding as `list-buffer`.

![image](https://user-images.githubusercontent.com/1134/129463332-08fd4b18-8646-4211-bd72-a06d4f2ddfed.png)

Is there something I'm missing?

**Comment by DogLooksGood** [comment]
Hi, 

We use `SPC x` to enter KEYPAD mode, but the first `SPC` key doesn't represent `C-`, it's the leader key in NORMAL/MOTION mode. For the case `SPC x b`, the input in KEYPAD mode is `x b`, which means `C-x C-b`.

`C-x b` is `C-x` + `literal b`, so it should be `x SPC b`(SPC is the literal prefix). Only when there's no binding on `C-x C-b`, the literal prefix can be omitted.

**Comment by bdarcus** [comment]
OK, that helps; thank you!

A few followups:

First, where do the mappings for that menu come from? I was assuming it would be dynamically generated a la which-key?

Second, why is there the "C-x" at the bottom? I was interpreting that as suggesting that the bindings above it relate to that.

![image](https://user-images.githubusercontent.com/1134/129464789-79d88f7f-8ff8-41f7-b203-b92b676b977c.png)

Third, the `meow-leader-define-key` is definitely ideal for this example (thanks for that), but if there a way to get a menu display for just `SPC`; to show the top-level leader bindings? I guess that might be tricky from a UX-perspective?

**Comment by DogLooksGood** [comment]
Hi,

> First, where do the mappings for that menu come from? I was assuming it would be dynamically generated a la which-key?

The menu is implemented in Meow. It is dynamically generated.

For your 2nd & 3rd question.

I guest you want to know where to find the suggestion for keybindings like `C-x b`? Just append an literal prefix by press `SPC`. Then popup menu will update.

![image](https://user-images.githubusercontent.com/11796018/129477501-ca627bdc-b525-4dcd-a839-05296db3bec3.png)

And yes, there will be a UX problem if display all the possible keybindings. 
There are 4 cases for your each input in KEYPAD mode: 

- no prefix means `C-`
- prefix `SPC` means no modifier to apply
- prefix `m` means `M-`
- prefix `g` means `C-M-`

After you input a prefix, you get the updated menu.
