### ISSUE TITLE
在不同的mode中，如何使用meow-leader来引专有的指令？

### ISSUE THREAD

**Issue by instinct2m** [DogLooksGood/meow#68]
例如，我在org-mode中，想用"<SPC> o s" 来绑定一个org-mode的专有指令，
而当我在java-mode中，我依旧用"<SPC> o s" 来绑定一个java-mode的指令。

或者换一个角度讲，在use-package中的：bind中如何引用meow-leader?
-------------------------原配置------------------------------->
(use-package org-download
 :bind
 (:map org-mode-map
        ("C-o s" . org-download-screenshot)))
(use-package lsp-mode
 : :bind 
  (:map java-mode-map
        ("C-o s" . lsp-java-assign-statement-to-local)))
-----------------------------引用后--------------------------->
(use-package org-download
 :bind
 (:map org-mode-map
        ("<meow-leader> o s" . org-download-screenshot)))
(use-package lsp-mode
 : :bind 
  (:map java-mode-map
        ("<meow-leader> o s" . lsp-java-assign-statement-to-local)))
----------------------------------------------------------------

我现在的解决方法在meow-leader-define-key中定义不冲突的全局快捷键。
所以造成的结果是，即使我在java-mode中，在用meow-leader时，依旧会出现org的引导
![2021-09-08_19-08](https://user-images.githubusercontent.com/32565852/132499098-9f36cb86-a0d8-422a-80ec-2c0a7154c192.png)

接触emacs主要用来记日程，所以很多细节不清楚，给您添麻烦了，希望可以指点一下。
看了下源码，很多地方看不懂，但是有一些简单的流程能明白，在meow-helpers中，发现
![2021-09-08_19-19](https://user-images.githubusercontent.com/32565852/132500487-b002fea2-981f-4d06-b769-246ef44e22c0.png)
但是找不到相关的定义。

麻烦您了，谢谢谢谢～～～

**Comment by instinct2m** [comment]
网页隐藏 尖括号的相关内容 ，我重新编写一份

例如，我在org-mode中，想用"**meow-leader**  o s" 来绑定一个org-mode的专有指令，
而当我在java-mode中，我依旧用"**meow-leader** o s" 来绑定一个java-mode的指令。

或者换一个角度讲，在use-package中的：bind中如何引用meow-leader?
-------------------------原配置------------------------------->
(use-package org-download
:bind
(:map org-mode-map
("C-o s" . org-download-screenshot)))
(use-package lsp-mode
: :bind
(:map java-mode-map
("C-o s" . lsp-java-assign-statement-to-local)))
-----------------------------引用后--------------------------->
(use-package org-download
:bind
(:map org-mode-map
("**meow-leader**  o s" . org-download-screenshot)))
(use-package lsp-mode
: :bind
(:map java-mode-map
("**meow-leader** o s" . lsp-java-assign-statement-to-local)))

表述的不清楚，望见谅。

**Comment by DogLooksGood** [comment]
你可以使用两段 \`\`\` 来包围你的代码块。参见 markdown 的语法。

类似于
```
let a = 1;
```
---
关于你的问题，meow 不支持不同 mode 下不同的 leader 绑定，因为 meow 本身就是为了解决这样的复杂情况的。
这个问题是通过 keypad 调用普通的快捷键来解决的。比如 java-mode 中 <kbd>C-c C-c</kbd> 是命令 A，而在 org-mode 中是命令 B。那么你都可以通过 <kbd>SPC c c</kbd> 来输入。见 [KEYPAD 相关的部分](https://github.com/DogLooksGood/meow/blob/master/README_CN.md#5-keypad-%E6%A8%A1%E5%BC%8F%E4%BB%A5%E4%B8%8D%E6%8C%89%E4%BF%AE%E9%A5%B0%E9%94%AE%E7%9A%84%E6%96%B9%E5%BC%8F%E8%BE%93%E5%85%A5%E7%BB%84%E5%90%88%E9%94%AE%E5%91%BD%E4%BB%A4)。

**Comment by instinct2m** [comment]
看了您的讲解，脑子突然转过弯来，我更能明白meow的强大之处了。
谢谢谢谢～
markdown的语法也受教了。
