### ISSUE TITLE
Which key bindings are for block editing?

### ISSUE THREAD

**Issue by zenny** [DogLooksGood/meow#7]
@DogLooksGood I am encountering the following practical issues:

A. In n/vim/kakoune or `evil-mode` there is a mode as follows in normal mode (SOLVED)

Go to top: `gg` (UPDATE: `<` in `meow`)
Go to bottom `G`(UPDATE: `>` in `meow`)
Go to the beginning of line: `0` (UPDATE: `s` in `meow`)
Go to the end of line: `$` (UPDATE: `t` in `meow`)

B. Emacs configuration I use is scimax which has by default `C-+` (though I prefer `C-=`) to increase font size and `C--` to decrease the font size, but it stops working once I activate `meow-mode`. How can one increase and decrease font size in `meow`?

C. In addition, there is a visual mode which allows you to select a block and make modifications with the following sequence:

1. `C-v` for visual mode
2. Visual selection either with cursor or mouse
3. `I` for `block insert` mode
4. type anything to insert
5. Press `Esc` to manifest in all lines selected in above 2.

I could not figure out the above possibilities in `meow-mode`. Did I miss something that can be done the other way round in this mode? I am on qwerty keyboard, fyi.

**Comment by DogLooksGood** [comment]
Sorry for reply so late.

> B. Emacs configuration I use is scimax which has by default C-+ (though I prefer C-=) to increase font size and C-- to decrease the font size, but it stops working once I activate meow-mode. How can one increase and decrease font size in meow?

The default shortcut in Emacs for increase/decrease font size are `C-x C-+` and then you can use `+`, `-` and `0` to adjust font size. So in Meow you can press `SPC x +`, then use `+`, `-` and `0`. Basically, since most Emacs shortcut is located under `C-x` and `C-c`, Meow use `SPC x`(or `x` without selection) and `SPC c`(or `c` without selection) to enter KEYPAD mode(the Kommand mode).

> C. In addition, there is a visual mode which allows you to select a block and make modifications with the following sequence:

There's no such stuff in Meow. I'm been thing how to do multi-editing for a while. There are so many methods in Emacs:
- built-in `cua-mode`
- multiple-cursors
- iedit
- kmacros
- built-in `query-replace`/`query-replace-regexp`

At the beginning I prefer to use multiple-cursors, but it has so many edge cases. Now I use kmacros and built-in query replace(or anzu -- enhancement for query replace). For editor like kakoune, which have a underlying built-in multiple selection support, that's another story.

**Comment by zenny** [comment]
> Sorry for reply so late.
> 
> > B. Emacs configuration I use is scimax which has by default C-+ (though I prefer C-=) to increase font size and C-- to decrease the font size, but it stops working once I activate meow-mode. How can one increase and decrease font size in meow?
> 
> The default shortcut in Emacs for increase/decrease font size are `C-x C-+` and then you can use `+`, `-` and `0` to adjust font size. So in Meow you can press `SPC x +`, then use `+`, `-` and `0`. Basically, since most Emacs shortcut is located under `C-x` and `C-c`, Meow use `SPC x`(or `x` without selection) and `SPC c`(or `c` without selection) to enter KEYPAD mode(the Kommand mode).

Thanks for the pointer. 

> 
> > C. In addition, there is a visual mode which allows you to select a block and make modifications with the following sequence:
> 
> There's no such stuff in Meow. I'm been thing how to do multi-editing for a while. There are so many methods in Emacs:
> 
>     * built-in `cua-mode`
> 
>     * multiple-cursors
> 
>     * iedit
> 
>     * kmacros
> 
>     * built-in `query-replace`/`query-replace-regexp`
> 
> 
> At the beginning I prefer to use multiple-cursors, but it has so many edge cases. Now I use kmacros and built-in query replace(or anzu -- enhancement for query replace). For editor like kakoune, which have a underlying built-in multiple selection support, that's another story.

Any pointer to your customization appreciated?!

**Comment by DogLooksGood** [comment]
Hi, I use `query-replace-regexp`  for simple text replace, bound to <kbd>/</kbd> in meow, the command is `meow-query-replace` which call underlying command that bound to <kbd>C-M-%</kbd>.  So if I want to replace `foo-bar` with `baz` in following text.
```
(defun f (foo-bar)
  (print foo-bar))
```

(I'm using dvorak keymap) I'll mark the `foo-bar` with <kbd>e</kbd>, copy it with <kbd>c</kbd>, then hold <kbd>b</kbd> to select the whole defun, then use <kbd>/</kbd> for `meow-query-replace`, then paste with <kbd>C-y</kbd>, ...

For complex operations, I use kmacro. I have these keybindings for recording keyboard macro and apply macro to lines in a region.
```
(meow-normal-define-key
   '("S" . kmacro-start-macro)
   '("E" . kmacro-end-macro)
   '("A" . apply-macro-to-region-lines)
   '("M" . kmacro-call-macro))
```

Glad to know your opinion about multiple editing.

**Comment by zenny** [comment]
> Hi, I use `query-replace-regexp` for simple text replace, bound to / in meow, the command is `meow-query-replace` which call underlying command that bound to C-M-%. So if I want to replace `foo-bar` with `baz` in following text.
> 
> ```
> (defun f (foo-bar)
>   (print foo-bar))
> ```
> 
> (I'm using dvorak keymap) I'll mark the `foo-bar` with e, copy it with c, then hold b to select the whole defun, then use / for `meow-query-replace`, then paste with C-y, ...
> 
> For complex operations, I use kmacro. I have these keybindings for recording keyboard macro and apply macro to lines in a region.
> 
> ```
> (meow-normal-define-key
>    '("S" . kmacro-start-macro)
>    '("E" . kmacro-end-macro)
>    '("A" . apply-macro-to-region-lines)
>    '("M" . kmacro-call-macro))
> ```
> 
> Glad to know your opinion about multiple editing.

Thanks. However, I miss the ease of home-row visual editing part of vim to be honest which is provided by evil-mode.
