### ISSUE TITLE
need help to hunderstand the  <{> <[> <}> for querty

### ISSUE THREAD

**Issue by julienJean99** [DogLooksGood/meow#8]
hi I started to use your package today and I'm having a few issues

I use the qwerty layout and in normal mode the <{> seems to be acting like the <M-{> in vanilla emacs and for <[> / <}> they do nothing and the <? k }>, for example, is not descriptive enough for me to understand what it is supposed to do (it only talk about barfing witch I don't know what it means in the context of emacs because otherwise ew).

do you have any idea this is happening? what are those key bindings supposed to do?

otherwise great package!

**Comment by DogLooksGood** [comment]
Sorry, I spent most of the time refactoring meow, and a lot commands changed. For the old version, those commands are used to wrap with parentheses. It's desiged(in the past), use `(`, `[`, `{` for wraping, and `)`, `}` for slurp and barf. 

Now meow don't provide a default keybindings.
